---
- name: Prepare
  hosts: all
  become: true
  tasks:
    - name: "Include ednz_cloud.install_docker"
      ansible.builtin.include_role:
        name: ednz_cloud.install_docker
      vars:
        install_docker_python_packages: true
